environment:
  env_id: "two-way-v0"
  render_mode: "human"
  dt: 0.2
  max_episode_steps: 200
  observation_type: "Kinematics"
  vehicles_count: 8
  collision_reward: -10.0
  high_speed_reward: 0.1
  normalize_reward: true
  offroad_terminal: false
  right_lane_reward: 0.3
  lanes_count: 4
  lane_width: 4.0
  screen_width: 900
  screen_height: 700
  scaling: 6.0
  show_trajectories: true
  simulation_frequency: 15
  policy_frequency: 5
  other_vehicles_type: "highway_env.vehicle.behavior.IDMVehicle"

agents:
  num_agents: 2
  observation_space:
    features: true
    vehicles_count: 10
  action_space:
    discrete: true
    actions:
      - IDLE
      - SLOWER
      - FASTER
      - LANE_LEFT
      - LANE_RIGHT

training:
  algorithm: "VPG"
  learning_rate: 0.0003
  gamma: 0.99
  epochs: 1
  episodes_per_epoch: 10
  batch_size: 64
  epsilon_start: 0.5
  epsilon_end: 0.05
  epsilon_decay: 0.995

network:
  hidden_layers: [256, 128]
  activation: "relu"

logging:
  log_interval: 1
  checkpoint_interval: 1
  tensorboard: false 