# HighwayEnv Configuration
environment:
  env_id: "two-way-v0"  # Two-way traffic environment with oncoming vehicles
  render_mode: "human"
  dt: 0.2  # Increased timestep for smoother simulation
  max_episode_steps: 200
  observation_type: "Kinematics"
  vehicles_count: 8  # More vehicles for realistic traffic
  
  # Additional environment-specific parameters
  collision_reward: -10.0
  high_speed_reward: 0.1   # Reduced speed reward to encourage safer driving
  normalize_reward: true
  offroad_terminal: false  # Prevent early termination when slightly off road
  right_lane_reward: 0.3   # Higher reward for staying in the right lane
  
  # Lane configuration
  lanes_count: 4  # 2 lanes in each direction
  lane_width: 4.0  # Wider lanes for better visibility
  
  # Additional visual and behavior settings
  screen_width: 900
  screen_height: 700
  scaling: 6.0  # Increased scaling for better visualization
  show_trajectories: true
  
  # Vehicle dynamics
  simulation_frequency: 15  # Higher sim frequency for smoother control
  policy_frequency: 5      # Lower policy frequency for smoother movement
  other_vehicles_type: "highway_env.vehicle.behavior.IDMVehicle"
  
# Agent Configuration
agents:
  num_agents: 2  # Two distinct agents
  observation_space:
    features: true
    vehicles_count: 10  # Increased to observe more vehicles
  action_space:
    discrete: true
    actions:
      - IDLE
      - SLOWER
      - FASTER
      - LANE_LEFT
      - LANE_RIGHT
  
# Training Configuration
training:
  algorithm: "VPG"
  learning_rate: 0.0003
  gamma: 0.99
  epochs: 500
  episodes_per_epoch: 5  # Reduced for quicker visualization cycles
  batch_size: 64
  epsilon_start: 0.5  # Lower initial exploration for less randomness
  epsilon_end: 0.05
  epsilon_decay: 0.995
  
# Neural Network Configuration
network:
  hidden_layers: [256, 128]
  activation: "relu"
  
# Logging Configuration
logging:
  log_interval: 10
  checkpoint_interval: 50
  tensorboard: true
